--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_user; Type: TABLE; Schema: public; Owner: tholde
--

CREATE TABLE public.account_user (
    usercode integer NOT NULL,
    fullname character varying(250) NOT NULL,
    email character varying(250) NOT NULL,
    password character varying(250) NOT NULL
);


ALTER TABLE public.account_user OWNER TO tholde;

--
-- Name: account_user_usercode_seq; Type: SEQUENCE; Schema: public; Owner: tholde
--

ALTER TABLE public.account_user ALTER COLUMN usercode ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_user_usercode_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: tholde
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO tholde;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: tholde
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: tholde
--

CREATE TABLE public.users_user (
    usercode integer NOT NULL,
    fullname character varying(250) NOT NULL,
    email character varying(250) NOT NULL,
    password character varying(250) NOT NULL
);


ALTER TABLE public.users_user OWNER TO tholde;

--
-- Name: users_user_usercode_seq; Type: SEQUENCE; Schema: public; Owner: tholde
--

ALTER TABLE public.users_user ALTER COLUMN usercode ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_usercode_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_user; Type: TABLE DATA; Schema: public; Owner: tholde
--

COPY public.account_user (usercode, fullname, email, password) FROM stdin;
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: tholde
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	users	0001_initial	2024-05-15 08:14:29.727362+03
2	account	0001_initial	2024-05-15 12:21:37.747627+03
3	users	0002_alter_user_email_alter_user_usercode	2024-05-15 14:59:16.428416+03
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: tholde
--

COPY public.users_user (usercode, fullname, email, password) FROM stdin;
8	Ladina	ladinasedera@gmail.com	pbkdf2_sha256$720000$D1YoAjNpoa3nuQGkh2dJDU$YX19Jk5cmAO1nr5hQcIDu7qCfKTrzMc7h0EOVjh5KL8=
9	Ladina	ladinasedera@gmail.com	pbkdf2_sha256$720000$FuyZGDft7BUCL97d8Z5DNw$8Y7FLdsrHozf6n1SUZT898zwAMwfrdiX6wLafWmR5Gs=
10	Ladina	ladinasedera@gmail.com	pbkdf2_sha256$720000$LYlNbZOEGR5b9pEhC40ZZP$fam8v9munfaCWqsttqnh/LJDPSuMEHitjt6ybEA5PgQ=
13	Tholde Rahalahifaliako	tholde.rahalahifaliako@gmail.com	pbkdf2_sha256$720000$3qeerdxSYmomUB1XqcUSTS$gKiquuwndN/LdVAo2jCVkbrWUAA4fX0oztg8c9LQUgA=
14	Tholde Navajoh	tholde.navajoh@gmail.com	pbkdf2_sha256$720000$ZHXvh8nz5qaDwUd0ydYQIu$ySYe/5tyf4OyZuWyQjGqbVTSe4dsAjS4DIePVEHOhrw=
12	Rakoto	rakoto@gmail.com	pbkdf2_sha256$720000$JwPKPYhQNKlol2pIIMX1MO$g99EqFq6RAqC7qRiSRJyAYadwvso+jIubo8zsDD/m5Y=
\.


--
-- Name: account_user_usercode_seq; Type: SEQUENCE SET; Schema: public; Owner: tholde
--

SELECT pg_catalog.setval('public.account_user_usercode_seq', 1, false);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tholde
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 3, true);


--
-- Name: users_user_usercode_seq; Type: SEQUENCE SET; Schema: public; Owner: tholde
--

SELECT pg_catalog.setval('public.users_user_usercode_seq', 14, true);


--
-- Name: account_user account_user_pkey; Type: CONSTRAINT; Schema: public; Owner: tholde
--

ALTER TABLE ONLY public.account_user
    ADD CONSTRAINT account_user_pkey PRIMARY KEY (usercode);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: tholde
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: tholde
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (usercode);


--
-- PostgreSQL database dump complete
--

